### ISSUE TITLE
numerous incompatibilities with bazel 0.24.0+

### ISSUE THREAD

**Issue by ixdy** [kubernetes/repo-infra#108]
It looks like bazel 0.24.0 flipped a number of flags that broke things in this repo:
* `--incompatible_disallow_dict_plus` was enabled by default, resulting in `go_genrule` breaking:
```
ERROR: ... in _go_genrule rule //staging/src/k8s.io/apimachinery/pkg/util/sets:set-gen:
Traceback (most recent call last):
        File ".../k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/sets/BUILD", line 25
                _go_genrule(name = 'set-gen')
        File ".../external/io_k8s_repo_infra/defs/go.bzl", line 82, in _go_genrule_impl
                ctx.action(inputs = (list(all_srcs) + resol...), <5 more arguments>)
        File ".../external/io_k8s_repo_infra/defs/go.bzl", line 85, in ctx.action
                ctx.configuration.default_shell_env + go.env
The `+` operator for dicts is deprecated and no longer supported. Please use the `update` method instead. You can temporarily enable the `+` operator by passing the flag --incompatible_disallow_dict_plus=fals
```
* The `pkg_tar` Starlark implementation seems to be [including `-mtime` now](https://github.com/bazelbuild/bazel/commit/25d202fc1545f4aaba821df75a8bf3fb57284da1):
```
flag provided but not defined: -mtime
Usage of bazel-out/host/bin/external/io_k8s_repo_infra/tools/build_tar/linux_amd64_stripped/build_tar:
  -compression gz
        Compression (gz or `bz2`), default is none.
  -deb value
        A debian package to add to the layer
  -directory string
        Directory in which to store the file inside the layer
  -file value
        A file to add to the layer
  -flagfile string
        Path to flagfile
  -link value
        Add a symlink a inside the layer ponting to b if a:b is specified
  -mode string
        Force the mode on the added files (in octal).
  -modes value
        Specific mode to apply to specific file (from the file argument), e.g., path/to/file=0455.
  -output string
        The output file, mandatory
  -owner string
        Specify the numeric default owner of all files, e.g., 0.0 (default "0.0")
  -owner_name string
        Specify the owner name of all files, e.g. root.root.
  -owner_names value
        Specify the owner names of individual files, e.g. path/to/file=root.root.
  -owners value
        Specify the numeric owners of individual files, e.g. path/to/file=0.0.
  -tar value
        A tar file to add to the layer
Target //build/release-tars:release-tars failed to build
```
  (See also https://github.com/kubernetes/repo-infra/issues/100)
* The `cc_toolchain` rule seems to have changed its attributes; trying to cross-compile gives lots of errors about missing attributes. (Might be related to https://github.com/bazelbuild/bazel/issues/6861?)

There might be other issues, these were just the first ones I noticed.

**Comment by ixdy** [comment]
For 3, it looks like the only issue (for now) is that the `dynamic_runtime_libs` and `static_runtime_libs` attributes on `cc_toolchain` changed to `dynamic_runtime_lib` and `static_runtime_lib`, i.e. they became singular.

It looks like this switch occurred in bazel 0.22; bazel 0.21 complains if we try to use the singular attributes. It looks like kubekins is using bazel 0.21, so we'll probably need to update that first.
