### ISSUE TITLE
type 'depset' is not iterable. Use the `to_list()` method to get a list

### ISSUE THREAD

**Issue by javier-b-perez** [kubernetes/repo-infra#119]
bazel --version
bazel 0.28.0

I see this error when I try to use push-build (from k8s master):

ERROR: /home/jbperez/go/src/k8s.io/kubernetes/BUILD.bazel:39:1: in gcs_upload rule //:push-build: 
Traceback (most recent call last):
	File "/home/jbperez/go/src/k8s.io/kubernetes/BUILD.bazel", line 39
		gcs_upload(name = 'push-build')
	File "/home/jbperez/.cache/bazel/_bazel_jbperez/770a5393ec0b756d4b1d36719db44027/external/io_k8s_repo_infra/defs/build.bzl", line 20, in _gcs_upload_impl
		for f in t.files: ...
type 'depset' is not iterable. Use the `to_list()` method to get a list. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.
ERROR: Analysis of target '//:push-build' failed; build aborted: Analysis of target '//:push-build' failed; build aborted

**Comment by javier-b-perez** [comment]
This is not the end:
ctx.file_action(output = ctx.outputs.targets, cont...))
Use ctx.actions.write instead of ctx.file_action. 
Use --incompatible_new_actions_api=false to temporarily disable this check.

**Comment by javier-b-perez** [comment]
INFO: Build completed successfully, 869 total actions
Traceback (most recent call last):
  File "../io_k8s_repo_infra/defs/gcs_uploader", line 340, in <module>
    Main()
  File "../io_k8s_repo_infra/defs/gcs_uploader", line 330, in Main
    os.execv(args[0], args)
OSError: [Errno 2] No such file or directory: '/home/jbperez/.cache/bazel/_bazel_jbperez/770a5393ec0b756d4b1d36719db44027/execroot/io_k8s_kubernetes/bazel-out/k8-fastbuild/bin/push-build.runfiles/bazel_tools/tools/python/py3wrapper.sh'
